-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 16:09:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_rede_social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_rede_social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_rede_social` DEFAULT CHARACTER SET utf8 ;
USE `db_rede_social` ;

-- -----------------------------------------------------
-- Table `db_rede_social`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rede_social`.`tb_tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(255) NOT NULL,
  `nivel` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_rede_social`.`tb_usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rede_social`.`tb_usuário` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `perfil` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_rede_social`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rede_social`.`tb_postagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `like` BIGINT NULL,
  `tb_tema_id` BIGINT NOT NULL,
  `tb_usuário_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagem_tb_tema_idx` (`tb_tema_id` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_usuário1_idx` (`tb_usuário_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_tema`
    FOREIGN KEY (`tb_tema_id`)
    REFERENCES `db_rede_social`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_usuário1`
    FOREIGN KEY (`tb_usuário_id`)
    REFERENCES `db_rede_social`.`tb_usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
